enableTransparentWorkspaces: false

packageExtensions:
  '@aws-sdk/lib-storage@*':
    dependencies:
      '@aws-sdk/smithy-client': '*'
  axios@*:
    dependencies:
      debug: '*'
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: 'https://raw.githubusercontent.com/toss/yarn-plugin-workspace-since/main/bundles/%40yarnpkg/plugin-workspace-since.js'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

# CI 의존성 설치 스크립트에서 --immutable-cache 옵션을 줬을 때,
# 캐시된 파일이 존재함을 예상했지만 없어서 에러("Cache entry required but missing")가 나는 부분을 해결하기 위해
# OS에 따른 분기처리를 진행합니다.
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.2.3.cjs
