name: Check Label
on:
  pull_request:
    types: [ labeled, unlabeled ]

jobs:
   check-label:
    runs-on: ubuntu-latest
    steps:
      - name: auto merge 끄기
        if: "contains( github.event.pull_request.labels.*.name, 'no-auto-merge')"
        run: gh pr merge --disable-auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}

      - name: auto merge 다시 켜기
        if: "!contains( github.event.pull_request.labels.*.name, 'no-auto-merge')"
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}