name: Deploy

on:
  push:
    branches:
      - 'dev'

jobs:
  ci:
    name: Dev
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
      NEXT_PUBLIC_GA_ID: ${{ secrets.GA_ID }}
      NEXT_PUBLIC_HJID: ${{ secrets.HOTJAR_HJID }}
      NEXT_PUBLIC_HJSV: ${{ secrets.HOTJAR_HJSV }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Run Build
        run: pnpm build

      - name: Express Init
        run: curl http://${{ secrets.HOST_DEV }}:8080/init

      - name: 빌드 폴더 생성
        run: mkdir -p ./builds/

      - name: 빌드 파일을 압축
        run: tar -czv .next > ./builds/.next.tar.gz

      - name: 빌드 파일을 EC2로 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_DEV_KEY }}
          source: './builds/.next.tar.gz'
          target: '/home/${{ secrets.AWS_USER_NAME }}/'

      - name: Express Deploy
        run: curl http://${{ secrets.HOST_DEV }}:8080/deploy
